# fly.toml app configuration file generated for hot-tips on 2026-05-25T12:40:36+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'hot-tips'
primary_region = 'cdg'

[build]
  dockerfile = 'Dockerfile'
  build-target = 'prod'

[env]
  DJANGO_DB_PATH = '/data/db.sqlite3'
  DJANGO_DEBUG = 'false'
  PORT = '8000'

[[mounts]]
  source = 'hot_tips_data'
  destination = '/data'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    type = 'requests'
    hard_limit = 60
    soft_limit = 30

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
