# Generated by Django 5.2.14 on 2026-05-24 01:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fighter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Matchup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('fighter_a', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matchups_as_a', to='arena.fighter')),
                ('fighter_b', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matchups_as_b', to='arena.fighter')),
            ],
            options={
                'ordering': ['sort_order', 'fighter_a__name', 'fighter_b__name'],
            },
        ),
        migrations.CreateModel(
            name='TipDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200, unique=True)),
                ('tip_type', models.CharField(choices=[('fighter', 'Fighter'), ('matchup', 'Matchup')], max_length=20)),
                ('modifier', models.SmallIntegerField()),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('fighter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fighter_tip_definitions', to='arena.fighter')),
                ('matchup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tip_definitions', to='arena.matchup')),
                ('target_fighter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='targeted_tip_definitions', to='arena.fighter')),
            ],
            options={
                'ordering': ['tip_type', 'sort_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='DailyTipSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_daily_tips', to=settings.AUTH_USER_MODEL)),
                ('tip', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='arena.tipdefinition')),
            ],
            options={
                'ordering': ['date', 'tip__sort_order', 'tip__label'],
            },
        ),
        migrations.CreateModel(
            name='DailyTipAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('action', models.CharField(choices=[('activate', 'Activate'), ('deactivate', 'Deactivate')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('tip', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='arena.tipdefinition')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='matchup',
            constraint=models.CheckConstraint(condition=models.Q(('fighter_a', models.F('fighter_b')), _negated=True), name='matchup_fighters_must_differ'),
        ),
        migrations.AddConstraint(
            model_name='matchup',
            constraint=models.UniqueConstraint(fields=('fighter_a', 'fighter_b'), name='unique_ordered_matchup'),
        ),
        migrations.AddConstraint(
            model_name='dailytipselection',
            constraint=models.UniqueConstraint(fields=('date', 'tip'), name='unique_shared_date_tip_selection'),
        ),
    ]
